# +-------------------------+
# | +---------------------+ |
# | |    Enchantments+-   | |
# | +---------------------+ |
# +-------------------------+
#                                                                                     -#-
# This is the configuration file for Enchantments+-.
# Need help? Check the GitHub wiki: https://github.com/dsdd/EnchantmentsPlusMinus
#
# +------------------------+
# |                        |
# |     Configuration      |
# |                        |
# +------------------------+
#
# Enchant configuration has been moved to the /enchants/ folder!
#
#                                                                             -#-

auto-update: false
show-enchants: true
show-enchant-descriptions: true
abbreviate-large-numbers: true
use-roman-numerals: false
open-enchant-gui-on-right-click: true
anvil-combining-enabled: true
use-vault-economy: false
use-action-bar-instead-of-chat-when-inventory-full: true
global-cost:
   enabled: false
   cost: 69420*%lvl%
enchant-lore-color: '&9'
apply-fortune-on:
- COAL
- LAPIS_LAZULI
- REDSTONE
- DIAMOND
- EMERALD
- QUARTZ
player-kill-reward:
   enabled: true
   min: 25
   max: 50
mob-kill-reward:
   enabled: true
   min: 5
   max: 10
mining-reward:
   enabled: true
   min: 25
   max: 50
   blockstobreak: 1000
enchant-specific-lore-color:
   depth_strider: null
do-not-add-lore-to:
- an item e.g. BEDROCK that you do not want lore added to due to plugin interference
disabled-enchants:
- an enchant you don't like